[project]
name = "streamlit-politics-sentiment-analysis"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "David Armendariz", email = "david.adrian.a.p@gmail.com"},
]
dependencies = ["tweepy>=4.16.0", "openai>=1.99.9", "python-dotenv>=1.1.1", "streamlit>=1.48.1", "pandas>=2.3.1"]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
